import { test } from 'node:test';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { temporary } from '../helpers.ts';

test('built stdio server preserves v1 tools and invokes all 27 tools through the official MCP client', { timeout: 30000 }, async t => {
  const home = temporary(t);
  const transport = new StdioClientTransport({ command: process.execPath,
    args: [fileURLToPath(new URL('../../dist/index.js', import.meta.url)), 'serve', '--home', home, '--namespace', 'contract'], stderr: 'pipe' });
  let logs = ''; transport.stderr?.on('data', data => { logs += String(data); });
  const client = new Client({ name: 'contract-client', version: '1.0.0' });
  await client.connect(transport);
  t.after(() => client.close());
  const tools = await client.listTools(); assert.equal(tools.tools.length, 27);
  for (const name of ['memory_add', 'memory_delete', 'memory_export', 'memory_get', 'memory_import', 'memory_list', 'memory_search', 'memory_update']) assert.ok(tools.tools.some(tool=>tool.name===name));
  const call = async (name: string, args: Record<string, unknown>) => {
    const response = await client.callTool({ name, arguments: args });
    assert.ok(!response.isError, JSON.stringify(response));
    return response.structuredContent as Record<string, unknown>;
  };
  const added = await call('memory_add', { content: 'unique-secret-looking-body-for-log-test', title: 'Contract', tags: ['mcp'] });
  const memory = added.memory as { id: string; source: string }; assert.equal(memory.source, 'contract-client');
  assert.equal((await call('memory_get', { id: memory.id })).title, 'Contract');
  assert.equal(((await call('memory_search', { query: 'Contract' })).memories as unknown[]).length, 1);
  assert.equal((await call('memory_list', {})).total, 1);
  await call('memory_update', { id: memory.id, updates: { importance: 9 } });
  const exported = await call('memory_export', { format: 'json' });
  assert.equal(exported.schemaVersion, 1);
  const preview = await call('memory_import', { format: 'json', data: exported.data, project: 'copy-scope', conflict: 'copy' });
  assert.equal(preview.dry_run, true);
  await call('memory_delete', { id: memory.id });
  const missing = await client.callTool({ name: 'memory_get', arguments: { id: memory.id } });
  assert.equal(missing.isError, true);
  assert.equal(((missing.structuredContent as { error: { code: string } }).error.code), 'NOT_FOUND');
  const invalid = await client.callTool({ name: 'memory_add', arguments: { content: ' ' } }); assert.equal(invalid.isError, true);
  await call('memory_restore',{ id:memory.id });
  assert.equal((await call('memory_stats',{})).active,1);
  const first=await call('entity_add',{ name:'Project A',type:'Project',aliases:['demo'] });
  const second=await call('entity_add',{ name:'SQLite',type:'Technology' });
  const a=(first.entity as {id:string}).id,b=(second.entity as {id:string}).id;
  assert.equal((await call('entity_get',{id:a})).name,'Project A');
  await call('entity_update',{id:a,updates:{aliases:['demo','test-project']}});
  assert.equal(((await call('entity_search',{query:'demo'})).entities as unknown[]).length,1);
  await call('entity_link',{memory_id:memory.id,entity_id:b});
  const fact=await call('relation_add',{source_entity_id:a,predicate:'USES',target_entity_id:b,valid_from:'2026-01-01T00:00:00Z',source_memory_id:memory.id});
  const relationId=(fact.relation as {id:string}).id;
  await call('relation_update',{id:relationId,updates:{confidence:.8}});
  assert.equal(((await call('relation_search',{})).relations as unknown[]).length,1);
  assert.equal(((await call('memory_at_time',{at:'2026-06-01T00:00:00Z'})).relations as unknown[]).length,1);
  assert.equal(((await call('graph_neighbors',{entity_id:a})).entities as unknown[]).length,2);
  assert.equal((await call('graph_path',{source_entity_id:a,target_entity_id:b})).found,true);
  assert.equal((await call('memory_search_hybrid',{query:'Contract'})).mode,'lexical');
  assert.equal((await call('memory_reindex',{})).enabled,false);
  assert.equal((await call('memory_enrich',{id:memory.id})).status,'disabled');
  await call('memory_find_duplicates',{id:memory.id});
  const other=await call('memory_add',{content:'Additional merge source'});
  const sourceId=(other.memory as {id:string}).id;
  const proposal=await call('memory_merge',{target_id:memory.id,source_ids:[sourceId]});
  assert.equal(proposal.dry_run,true);
  await call('memory_merge',{target_id:memory.id,source_ids:[sourceId],dry_run:false,proposal_token:proposal.proposal_token});
  assert.equal((await call('memory_maintenance',{action:'graph-check'})).invalid_relations,0);
  assert.ok(!logs.includes('unique-secret-looking-body-for-log-test'));
});
